language: java

jdk:
  - oraclejdk8

before_script:
  - chmod +x gradlew

script:
  - ./gradlew check --stacktrace --debug
  #- ./gradlew test

after_success:
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)