name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
    - name: Set up env vars
      env:
        KOTWAVE_CLIENTID: ${{ secrets.KOTWAVE_CLIENTID }}
        KOTWAVE_CLIENT_SECRET: ${{ secrets.KOTWAVE_CLIENT_SECRET }}
        KOTWAVE_USERNAME: ${{ secrets.KOTWAVE_USERNAME }}
        KOTWAVE_PASSWORD: ${{ secrets.KOTWAVE_PASSWORD }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Test with Gradle
      run: ./gradlew test --stacktrace --info
    - name: Generate Test report
      run: ./gradlew jacocoTestReport
    - name: Upload Test Report
      run: bash <(curl -s https://codecov.io/bash)
